title: Comparing Fixed and Variable Segment Durations for Adaptive Video Streaming
description: Comparing Fixed and Variable Segment Durations for Adaptive Video Streaming
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman